version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: genie-postgres
    restart: always
    environment:
      POSTGRES_USER: genieUser
      POSTGRES_PASSWORD: geniePassword
      POSTGRES_DB: genieDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: genie-redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: